name: nba_app
description: Check NBA scores and stats.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: any
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/team-logos/1.png
    - assets/team-logos/2.png
    - assets/team-logos/3.png
    - assets/team-logos/4.png
    - assets/team-logos/5.png
    - assets/team-logos/6.png
    - assets/team-logos/7.png
    - assets/team-logos/8.png
    - assets/team-logos/9.png
    - assets/team-logos/10.png
    - assets/team-logos/11.png
    - assets/team-logos/12.png
    - assets/team-logos/13.png
    - assets/team-logos/14.png
    - assets/team-logos/15.png
    - assets/team-logos/16.png
    - assets/team-logos/17.png
    - assets/team-logos/18.png
    - assets/team-logos/19.png
    - assets/team-logos/20.png
    - assets/team-logos/21.png
    - assets/team-logos/22.png
    - assets/team-logos/23.png
    - assets/team-logos/24.png
    - assets/team-logos/25.png
    - assets/team-logos/26.png
    - assets/team-logos/27.png
    - assets/team-logos/28.png
    - assets/team-logos/29.png
    - assets/team-logos/30.png
